src/pages/dataset-details-page/__snapshots__/dataset-details-page-pure.test.jsx.snap
src/pages/dataset-details-page/dataset-details-page-pure.jsx
src/pages/dataset-details-page/dataset-distribution/__snapshots__/dataset-distribution.component.test.jsx.snap
src/pages/dataset-details-page/dataset-distribution/dataset-distribution.component.jsx

feat: show distribution title

---

features/search.concept.feature

feat(specification): feature file for concept search

---

src/constants/constants.js

Husk å oppdatere snapshots om nødvendig

changed const url

---

src/pages/article-page/__snapshots__/article-page.component.test.jsx.snap
src/pages/article-page/article-page.component.jsx

changed email adress and updated link to pers

---

src/app/__snapshots__/app.test.jsx.snap
src/app/app.jsx
src/components/article/article.ts
src/components/article/components/article/article.component.tsx
src/components/article/components/article/styled.ts
src/constants/constants.js
src/pages/main-page/components/article-item/article-item.component.tsx
src/pages/main-page/components/article-item/styled.ts
src/pages/main-page/components/news-list/news-list-component.tsx
src/pages/main-page/main-page-pure.tsx
src/pages/main-page/news.json
src/pages/main-page/styled.ts
src/pages/news-article-page/news-article-page-pure.tsx
src/pages/news-article-page/news-article-page.ts
src/pages/news-article-page/styled.ts
src/pages/search-page/search-page-pure.jsx
src/types/domain.d.ts

add news article page

---

src/components/dataset-details-page/index.tsx
src/components/with-concepts/redux/actions.ts
src/components/with-concepts/redux/saga.ts
src/components/with-data-services/redux/actions.ts
src/components/with-data-services/redux/saga.ts
src/components/with-dataset/redux/action-types.ts
src/components/with-dataset/redux/actions.ts
src/components/with-dataset/redux/reducer.ts
src/components/with-datasets/redux/actions.ts
src/components/with-datasets/redux/saga.ts

Alternativ måte som sender "tom request" for å slette store. Ser ut som det er feil med endepunkter:
https://www.staging.fellesdatakatalog.digdir.no/api/concepts?identifiers= skal returnere tomt
https://www.staging.fellesdatakatalog.digdir.no/api/datasets?uris= skal returnere tomt

fix(dataset-details-page): #277 clear redux store on mount

---

src/app/__snapshots__/app.test.jsx.snap
src/components/article/components/article/article.component.tsx
src/components/dataset-details-page/index.tsx
src/components/dataset-distribution/components/dataset-distribution/index.tsx
src/components/dataset-distribution/components/summary/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/datasets-report-page/report-stats/__snapshots__/report-stats.component.test.jsx.snap
src/pages/datasets-report-page/report-stats/api-stats/api-stats.component.jsx
src/pages/datasets-report-page/report-stats/concept-stats/concept-stats.component.jsx
src/pages/datasets-report-page/report-stats/dataset-stats/dataset-stats.component.jsx
src/pages/datasets-report-page/report-stats/report-stats.component.jsx
src/pages/news-article-page/news-article-page-pure.tsx
src/types/domain.d.ts

prodsetting portal

---

src/app/app-nav-bar/app-nav-bar.jsx

Revert "feat: #331 add organizations to navbar"

---

src/pages/report-page/__snapshots__/report-page-pure.test.jsx.snap
src/pages/report-page/report-page-pure.jsx
src/pages/report-page/report-stats/report-stats.component.jsx

Fjerner fetch i child, gjøres allerede i parent og gir items som prop til child.

refactor(report-page): remove fetchCatalogsIfNeeded as prop from child

---

src/pages/search-page/results-api/__snapshots__/results-api.component.test.jsx.snap
src/pages/search-page/results-dataset/__snapshots__/results-dataset.component.test.jsx.snap
src/pages/search-page/results-informationmodel/__snapshots__/results-informationmodel.component.test.jsx.snap

This reverts commit 816dbe6b, gjorde npm i lokalt.

Revert "fix: update snapshots"

---

src/components/dataset-distribution/components/dataset-distribution/__tests__/index.test.tsx
src/components/dataset-distribution/components/dataset-distribution/index.tsx
src/types/domain.d.ts

- fix dataset distribution
- fix visning av underenheter for innholdsleverandører

prodset fdk-portal

---

src/pages/report-page/components/datasetReport/formatPie/formatPie.component.tsx

prodsett portal

---

.github/workflows/deploy-demo.yaml
.github/workflows/deploy-prod.yaml
.github/workflows/deploy-staging.yaml
src/components/dataset-details-page/index.tsx
src/components/with-datasets/redux/action-types.ts
src/components/with-datasets/redux/actions.ts
src/components/with-datasets/redux/reducer.ts
src/components/with-organization/redux/actions.ts
src/components/with-organization/redux/reducer.ts
src/components/with-organization/redux/saga.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/data-service-details-page/data-service-details-page.jsx
src/pages/organizations/pages/dataset-page/index.tsx
src/pages/organizations/pages/datasets-page/index.tsx
src/pages/organizations/pages/datasets-page/styled.ts
src/pages/organizations/pages/organization-page/index.tsx
src/pages/report-page/report-page-pure.jsx
src/types/domain.d.ts

Rapportside:
Oppdatert graf for rapportside-informasjonsmodeller
Metadatakvalitet:
oppdatert regel for tittel
ikke vise metadatakvalitet når det ikke finnes datasett
vise gjennomsnittet til virksomheten
styling
Datatjeneste detaljeside:
vise tjenestetype
Datasett detaljeside:
fikset relasjoner til andre datasett

Prodsetting portal v2

---

src/api/cms-api/article-entities.ts
src/api/search-fulltext-api/datasets.ts
src/app/__snapshots__/app.test.jsx.snap
src/components/statistics-regular/components/statistics-regular/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/informationmodel-details-page/information-model-details-page.jsx
src/pages/informationmodel-details-page/resolved-information-model-details-page.jsx
src/pages/report-page/components/conceptReport/conceptReport.component.tsx
src/pages/report-page/components/dataserviceReport/dataserviceReport.component.tsx
src/pages/report-page/components/datasetReport/datasetReport.component.tsx
src/pages/report-page/components/informationModelReport/informationModelReport.component.tsx
src/types/enums.ts

Rapportside:
- Tall på datatjenesterapporter fungerer nå som forventet
- Lenker til katalogert fungerer nå som forventet
- Lenker til antall virksomheter er nå disablet

prodsetting fdk-portal

---

src/components/analytics/index.tsx
src/types/enums.ts

feat(analytics): add SVV tracking-id for transport portal

---

src/components/analytics/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/enums.ts

- updated text strings
- updated google analytics for SVV

prodset portal

---

src/components/with-public-services/redux/actions.ts
src/components/with-public-services/redux/saga.ts

fix(with-public-services): add page and sortfield as search params

---

src/entrypoints/main/index.html
src/entrypoints/maintenance/index.html
src/entrypoints/publishing/index.html

La oss håpe det fikser cache problematikken!

fix: #766 add headers to HTML entrypoints to prevent caching

---

src/components/event-details-page/index.tsx
src/types/domain.d.ts
src/types/enums.ts

fix(event-details-page): add specializedType

---

src/components/with-organization/redux/saga.ts

En måte er å ha sjekk at man legger inn objekt i redux, ellers feiler det på toJS() når man henter ut.

fix(with-organization): check if organization is object

---

package-lock.json
package.json
src/components/with-event-types/redux/utils.ts
src/components/with-kartverket/redux/utils.ts

Fix: cors error

---

package-lock.json
package.json
src/components/concept-details-page/index.tsx
src/components/dataset-details-page/index.tsx
src/components/event-details-page/index.tsx
src/components/information-model-details-page/index.tsx
src/components/public-service-details-page/index.tsx

Fixes Informasjonsforvaltning/fdk-issue-tracker#218

Feat: markdown

---

src/app/__snapshots__/app.test.jsx.snap
src/app/app.jsx
src/app/connected-app.js
src/components/error-page/index.tsx
src/components/footer/index.tsx
src/components/header/index.tsx

fix: adds header and footer to root error page

---

package-lock.json
package.json

fix: updates package lock

---

package-lock.json
src/l10n/nb.json
src/l10n/nn.json

fix: replace nøkkelord with søkeord

---

src/components/information-model-details-page/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

Closes Informasjonsforvaltning/fdk-issue-tracker#242

feat: add uri type mapping

---

src/components/infomodel-structure/index.tsx
src/components/infomodel-structure/model-element-list/element/index.tsx
src/components/information-model-details-page/index.tsx

Closes Informasjonsforvaltning/fdk-issue-tracker#231

fix: adds iris for dataserivce information models

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

Fixes Informasjonsforvaltning/fdk-portal#832

fix: #832 change label

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

fix: #832 update label

---

src/components/with-public-service/redux/saga.ts

Informasjonsforvaltning/fdk-portal#851

fix: fail get if no data received

---

package-lock.json
src/components/dataset-distribution/components/dataset-distribution/__tests__/index.test.tsx
src/components/dataset-distribution/components/dataset-distribution/index.tsx
src/components/dataset-item/dataset-item.component.tsx
src/pages/main-page/main-page-pure.tsx
src/utils/mediatype/__tests__/index.test.ts
src/utils/mediatype/index.ts

fix: format mediatype

---

src/api/search-fulltext-api/datasets.ts
src/pages/organizations/pages/organization-page/index.tsx
src/pages/search-page/filter-pills/filter-pills.component.tsx
src/pages/search-page/search-page-pure.tsx
src/types/enums.ts

fix: #881 add filter parameter to allow filtering by organization number

---

src/api/organizations-api/organizations.ts
src/components/with-organization/redux/actions.ts
src/components/with-organization/redux/saga.ts
src/pages/organizations/pages/organization-page/index.tsx

fix: #884 add missing filter parameter for Transportportal

---

src/pages/search-page/search-page-pure.tsx

Fix at søk fungerer fra alle faner og oppdaterer count for samtlige faner.

fix(search-page): fetch all data when searching or filtering

---

src/api/search-fulltext-api/dataservices.ts

Closes Informasjonsforvaltning/fdk-issue-tracker#304

fix: applies oganization number filter for dataservices

---

src/pages/organizations/pages/organizations-page/index.tsx

Closes Informasjonsforvaltning/fdk-issue-tracker#309

fix: sorting in chrome

---

src/api/search-fulltext-api/concepts.ts
src/api/search-fulltext-api/informationmodels.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/organizations/pages/organization-page/index.tsx
src/pages/organizations/pages/organization-page/styled.ts
src/types/domain.d.ts

feat: #908 add summary boxes for concepts and information models

---

.eslintignore
Dockerfile
resources/questback.popup-1.0.1.min.js
src/entrypoints/main/index.html
webpack/base.config.ts

Serve script-fil fra questback selv.

chore(index.html): add script-file as resource

---

package-lock.json
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

rm theme deprecation message

---

package-lock.json
package.json

Bruker trikset til @matsjs, bygger i det minste lokalt nå

fix: able to download designsystemet dependency

---

src/api/search-fulltext-api/dataservices.ts
src/components/dataset-details-page/index.tsx
src/components/dataset-distribution/components/dataset-distribution/index.tsx
src/components/with-data-services/redux/actions.ts
src/components/with-data-services/redux/saga.ts
src/types/domain.d.ts

resolves #934 
Må gjøre noen endringer i registrering i tillegg, PR kommer der på mandag elns

feat: dataset details - search for access services

---

package-lock.json
package.json
src/components/article/components/article/article.component.tsx
src/components/markdown/index.tsx
src/components/markdown/styled.ts

fix: added markdown styling and html support for articles

---

src/components/markdown/styled.ts

chore: add cell padding

---

src/components/information-model-details-page/index.tsx

Closes Informasjonsforvaltning/fdk-issue-tracker#375

fix: do not link skolem, hide null version

---

src/api/search-fulltext-api/all-entities.ts
src/api/search-fulltext-api/concepts.ts
src/api/search-fulltext-api/dataservices.ts
src/api/search-fulltext-api/datasets.ts
src/api/search-fulltext-api/events.ts
src/api/search-fulltext-api/informationmodels.ts
src/api/search-fulltext-api/public-services-and-events.ts
src/api/search-fulltext-api/public-services.ts
src/components/with-concept/redux/saga.ts
src/components/with-data-service/redux/saga.ts
src/components/with-dataset/redux/saga.ts
src/components/with-event/redux/saga.ts
src/components/with-public-service/redux/saga.ts

fix: add null safety for fulltext queries

---

src/l10n/nn.json

fix: korrigering nynorsk

---

src/components/dataset-details-page/index.tsx

Closes Informasjonsforvaltning/dataset-catalog-gui#87

fix: only show keywords for selected language

---

src/components/information-model-details-page/index.tsx

Closes Informasjonsforvaltning/fdk-issue-tracker#325

feat: adds concept used about infomodel

---

src/pages/search-page/compare-list/index.tsx

Fixes Informasjonsforvaltning/fdk-issue-tracker#319

fix: use compare id list and null check

---

src/components/information-model-details-page/index.tsx
src/types/domain.d.ts

Closes  Informasjonsforvaltning/fdk-issue-tracker#325

fix: display correct subjects for information model

---

src/components/article/components/article/article.component.tsx

fix: extend default allowedTags with img

---

src/components/article/components/article/article.component.tsx

- Støtte html liste og linjeskift i artikler

Prodsetting

---

src/components/information-model-details-page/index.tsx

Closes Informasjonsforvaltning/fdk-issue-tracker#405

fix: display correct model subjects in structure

---

src/api/referenceData.js
src/components/data-service-details-page/index.tsx
src/components/with-reference-data/redux/saga.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/domain.d.ts

feat: new reference data api-specifications

---

src/components/spinner/index.tsx
src/components/spinner/styled.ts
src/components/with-organization/index.tsx
src/components/with-organization/redux/reducer.ts
src/images/spinner-digdir-fdk.svg
src/pages/organizations/pages/organization-page/index.tsx

#1016 Adding spinner for organization-page

---

src/entrypoints/publishing/components/header/styled.ts

Knyttet til #1027.
Fikser CSS'en på demologen. Resten kommer i egen PR (fix på undersidene)

fix: fixing style for demologo

---

src/components/concept-details-page/index.tsx

Close Informasjonsforvaltning/fdk-issue-tracker#437

chore: add markdown parsing to remark

---

src/components/error-page/components/error-400/index.tsx
src/components/spinner/styled.ts
src/components/with-organization/redux/reducer.ts
src/pages/organizations/pages/organization-page/index.tsx
src/pages/organizations/pages/organizations-page/index.tsx

chore: adds and centers loading spinner on org pages

---

src/components/dataset-details-page/index.tsx

fix: prune empty resources

---

src/components/empty-hits/empty.component.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

feat: adds path to community on empty hits

---

src/components/dataset-distribution/components/dataset-distribution/index.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/454

fix: rm lowercase view of distribution urls

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

Fixes: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/468

chore: change relationList text

---

src/app/app.jsx

fix: redirect if path is main and theme nap

---

src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx

- Fiks på datoformatering for henting av aktive driftsmeldinger

fix: use datetime iso format when fetching service messages

---

src/entrypoints/publishing/components/header/index.tsx

fix: publishing header should link to publishing root

---

src/entrypoints/main/index.html

Part of Informasjonsforvaltning/fdk-issue-tracker#499

feat: adds page preview image

---

src/pages/organizations/pages/organization-page/index.tsx
src/pages/organizations/pages/organization-page/styled.ts

Closes Informasjonsforvaltning/fdk-issue-tracker#506

chore: removes beta tag for organization details page

---

src/components/data-service-details-page/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/508

fix: redux reset datasets

---

src/components/details-page/components/banner/index.tsx
src/components/language-indicator/index.tsx
src/components/language-indicator/styled.ts
src/components/multilingual-field/components/multilingual-field/index.tsx
src/components/multilingual-field/components/multilingual-field/styled.ts

fix: center title language icon and use active language

---

src/api/user-feedback-api/comments.ts
src/components/community/comments/components/comment-card/index.tsx
src/components/community/comments/components/comment-card/styled.ts
src/components/community/comments/components/comment-page/index.tsx
src/components/community/comments/components/composer/index.tsx
src/components/community/comments/components/logOut/index.tsx
src/components/community/comments/index.tsx
src/components/community/comments/styled.ts
src/components/infomodel-structure/__tests__/__snapshots__/infomodel-structure.component.test.tsx.snap
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/domain.d.ts

feat: adds pagination to user feedback

---

audit-resolve.json
package-lock.json
package.json
src/components/concept-details-page/index.tsx
src/components/with-concept/redux/saga.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/services/api/harvester-bff/index.ts
src/types/domain.d.ts
src/types/enums.ts

Resolves https://github.com/informasjonsforvaltning/fdk-issue-tracker/issues/568 and #1180

Change concept-details endpoint and add concept relations

---

package-lock.json
src/l10n/nb.json
src/pages/main-page/main-page-pure.tsx
src/pages/search-page/search-page-pure.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/436

fix: change offentlig trasport to kollektivtransport

---

src/components/infomodel-structure/index.tsx

Resolves https://github.com/informasjonsforvaltning/fdk-portal/issues/1214

fix(infomodel-structure): fallback if string does not exist

---

src/components/dataset-details-page/index.tsx
src/types/domain.d.ts

Resolves https://github.com/informasjonsforvaltning/fdk-portal/issues/1233

fix(dataset-details-page): use correct field for dct:type

---

package-lock.json
src/components/community/community-container/styled.ts
src/components/community/post/index.tsx
src/components/truncated-text/index.tsx
src/components/truncated-text/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/main-page/main-page-pure.tsx

feat https://github.com/Informasjonsforvaltning/fdk-portal/issues/1244

feat: show latest comments from Data Community

---

src/api/referenceData.js
src/components/dataset-details-page/index.tsx
src/components/dataset-item/dataset-item.component.tsx
src/components/details-page/components/details-page/index.tsx
src/components/filter-option/filter-option.component.tsx
src/components/informationmodel-item/informationmodel-item.component.tsx
src/components/with-reference-data/redux/saga.ts
src/lib/los/los-helper.ts
src/pages/report-page/components/dataserviceReport/dataserviceReport.component.tsx
src/pages/report-page/components/datasetReport/datasetReport.component.tsx
src/pages/search-page/los-aggregations-helper.js
src/pages/search-page/results-all-entities/results-all-entities.component.tsx
src/redux/modules/referenceData.js
src/types/domain.d.ts
src/utils/common/index.ts
test/fixtures/filterOptions.js

chore: get all reference data from new api

---

src/pages/cms-information-page/styled.ts

fixes https://github.com/informasjonsforvaltning/fdk-issue-tracker/issues/595
fixes https://github.com/informasjonsforvaltning/fdk-portal/issues/1264
fixes https://github.com/informasjonsforvaltning/fdk-portal/issues/1266

fix(about-pages): side&drop-down menu, spacing

---

src/pages/report-page/components/datasetReport/datasetReport.component.tsx
src/pages/report-page/report-page-pure.tsx
src/types/domain.d.ts

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/610
Med bokmål som valgt språk:
med engelsk som valgt språk:

fix: handle catalog title translations from report-bff

---

src/components/header/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

fix: wcag  - remove redundant link

---

package-lock.json
src/entrypoints/main/index.html

closes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/640

chore: remove questback

---

src/components/search-box/components/search-link/__tests__/__snapshots__/search-link.component.test.tsx.snap
src/components/search-box/components/search-link/search-link.component.tsx
src/components/search-box/components/search-link/styled.ts

fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1381

fix: add tag title to anchor

---

src/api/datasetPreview.js
src/components/with-dataset-preview/redux/saga.ts
src/config.js
src/env.ts
src/utils/common/index.ts

chore: enable csrf

---

src/components/article/components/article/styled.ts

fix: #1312 constrast article header

---

src/pages/search-page/tabs/components/tabs/styled.ts

fix: #1310 text beta on  banner too small

---

src/components/public-service-details-page/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

Fix: Add text 'inngår i' before links in 'Related Events'-component 

---

src/components/public-service-details-page/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

fix: Added missing text and fixed link title for 'related service' component  

---

package-lock.json
package.json

refactor: replace deprecated node-sass dependency with sass

---

src/components/error-page/components/error-400/styled.ts
src/components/error-page/components/error-500/index.tsx
src/components/error-page/components/error-500/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

style: fixed text and responsive design (mobile view) for error 500 and error 400 pages

---

src/components/public-service-details-page/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/domain.d.ts

feat: closes #1415 add website for the service on details page

---

package-lock.json
package.json
src/components/details-page/components/banner/index.tsx
src/components/details-page/components/banner/styled.ts
src/components/details-page/components/details-page/index.tsx
src/components/details-page/components/details-page/styled.ts

fix: moved name of provider into the banner

---

src/components/search-box/components/search-link/search-link.component.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1381

fix: add non breaking space related to SEO

---

src/components/public-service-details-page/index.tsx
src/components/public-service-details-page/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/domain.d.ts
src/types/enums.ts

Update dokumentasjonskrav komponent with rdf values

---

package-lock.json
package.json
src/components/statistics-regular/components/illustration-with-count/styled.ts
src/components/statistics-regular/components/statistics-regular/styled.ts
src/pages/organizations/pages/organization-page/index.tsx
src/pages/organizations/pages/organization-page/styled.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1311

fix: wcag contrast + new icons

---

src/components/public-service-details-page/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/domain.d.ts

closes #1375 
Kommentar: Har ikke fått testet `<ScrollLink/>` ordentlig med data fordi det ikke finnes nok testdata, men troor logikken er riktig. (Den skal scrolle til relatert avsnitt i relaterte regelverk).

feat: add relatert regelverk information to public service details page

---

.npmrc
package-lock.json
src/components/dataset-distribution/components/summary/__tests__/styled.test.tsx
src/components/dataset-distribution/components/summary/styled.ts
src/components/details-page/components/details-page/styled.ts

fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1279

fix(details-page): main content overflow

---

src/components/language-indicator/styled.ts

fix: textLanguageLabel splittes i noen tilfeller i to linjer

---

src/components/details-page/components/banner/index.tsx
src/components/details-page/components/banner/styled.ts
src/components/details-page/components/details-page/index.tsx
src/components/public-service-details-page/index.tsx
src/types/domain.d.ts

feat: update banner on public service details page

---

src/components/box-regular/styled.ts
src/pages/report-page/components/conceptReport/conceptReport.component.tsx
src/pages/report-page/components/dataserviceReport/dataserviceReport.component.tsx
src/pages/report-page/components/datasetReport/datasetReport.component.tsx
src/pages/report-page/components/informationModelReport/informationModelReport.component.tsx
src/pages/report-page/styled.ts

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/584

fix(report-page): reduce spacing between components

---

src/components/public-service-details-page/index.tsx
src/types/domain.d.ts

chore: replace isClassifiedBy with subject

---

src/entrypoints/main/index.html
src/entrypoints/publishing/index.html

feat: add siteimprove script

---

src/components/article-item/styled.ts
src/components/article/components/article/styled.ts
src/components/article/components/vimeo-video/styled.ts
src/components/community/comments/components/composer/styled.ts
src/components/community/comments/styled.ts
src/components/concept-details-page/styled.ts
src/components/details-page/components/banner/styled.ts
src/components/infomodel-structure/model-element-list/styled.ts
src/components/public-service-details-page/styled.ts
src/components/search-hit/components/search-hit/styled.ts
src/entrypoints/publishing/router/publishing/pages/publishing-page/styled.ts
src/pages/cms-information-page/styled.ts
src/pages/organizations/pages/dataset-page/styled.ts

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/663

fix: set line-height min val for paragraphs

---

.eslintrc.json
package-lock.json
package.json
src/components/dataset-distribution/components/summary/index.tsx

Fikser delvis https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/667
Resten av issuet skal været fikset av andre prer, som er relatert til [https://data.norge.no/public-services/](https://data.norge.no/public-services/a0db7475-6f3a-3cc5-ab9d-287433589a00) og Strapi
fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1497

a11y(Summary): no empty heading

---

src/entrypoints/publishing/components/header/index.tsx
src/entrypoints/publishing/router/publishing/pages/service-message-page/index.tsx
src/pages/news-article-page-v2/news-article-page.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/675

fix: link missing a text alternative

---

src/components/public-service-details-page/index.tsx

Var litt irriterende at staging ikke fungerer, så har laget en midlertidig fiks for public service details page.

chore: fix to stop details page from breaking

---

src/components/details-page/components/banner/index.tsx
src/components/details-page/components/details-page/index.tsx
src/components/public-service-details-page/index.tsx
src/components/search-hit/components/search-hit/__tests__/__snapshots__/search-hit.component.test.tsx.snap
src/components/search-hit/components/search-hit/__tests__/search-hit.component.test.tsx
src/components/search-hit/components/search-hit/search-hit.component.tsx
src/components/with-organization/index.tsx
src/components/with-organization/redux/actions.ts
src/components/with-organization/redux/saga.ts
src/components/with-organizations-catalog/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/organizations/pages/datasets-page/index.tsx
src/pages/organizations/pages/organization-page/index.tsx
src/pages/search-page/compare-list/index.tsx
src/types/domain.d.ts

https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/212
closes #1473

feat: add compententAuthority to bruk av tjenesten

---

src/app/styles/common.ts
src/components/article-item/styled.ts
src/components/article/components/article/styled.ts
src/components/article/components/vimeo-video/styled.ts
src/components/community/comments/components/composer/styled.ts
src/components/community/comments/styled.ts
src/components/details-page/components/banner/styled.ts
src/components/infomodel-structure/model-element-list/styled.ts
src/components/public-service-details-page/styled.ts
src/components/search-hit/components/search-hit/styled.ts
src/entrypoints/publishing/router/publishing/pages/publishing-page/styled.ts
src/pages/cms-information-page/styled.ts
src/pages/organizations/pages/dataset-page/styled.ts

fixes: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/663

fix(a11y): define global <p> line-heigh

---

src/app/styles/common.ts
src/assets/designsystemet/scss/common.scss
src/assets/designsystemet/scss/mixins.scss
src/assets/designsystemet/scss/portal.scss
src/assets/designsystemet/scss/typo.scss
src/assets/fonts/icomoon.css
src/components/community/container-header/styled.ts
src/components/community/news-item/styled.ts
src/components/community/post/styled.ts
src/components/community/time-stamp/styled.ts
src/components/dataset-distribution/components/summary/styled.ts
src/components/details-page/components/banner/styled.ts
src/components/details-page/components/details-page/styled.ts
src/components/filter-box/filter-box.scss
src/components/search-box/components/search-form/styled.ts
src/components/search-hit-header/search-hit-header.scss
src/components/truncated-text/styled.ts
src/entrypoints/publishing/router/publishing/pages/publishing-page/styled.ts
src/entrypoints/publishing/router/publishing/pages/service-message-page/styled.ts
src/pages/organizations/pages/organization-page/styled.ts
src/pages/report-page/publishers-select/publishers-select.scss
src/pages/report-page/styled.ts
src/pages/search-page/filter-pills/styled.ts

- make all line-heights unitless
- set default min line-height to 1.5
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/663

fix: set min line-height to 1.5 (unitless)

---

src/components/public-service-details-page/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/domain.d.ts

feat: implement component Deltakende

---

src/components/dataset-distribution/components/preview/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/693

fix: add reactdatagrid css

---

src/pages/search-page/filters/index.tsx

fix: aggregations conditional chaining

---

package.json
src/constants/constants.js
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/ai-project-page/index.tsx
src/pages/ai-project-page/styled.ts

Update title and preable of AI-oversikt

---

src/pages/ai-project-page/index.tsx

fix: add external icon to link

---

src/app/app-nav-bar/app-nav-bar.tsx
src/components/expansion-indicator-default/index.tsx
src/components/treeview/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

fixes #1537 
fixes #1534 (already done, just adding langstrings)

fix: mark external link in NAP

---

src/components/dropdown-menu/styled.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1588

fix: scrolling on mobile

---

src/components/pill/pill.component.tsx
src/components/pill/styled.ts
src/pages/search-page/filter-pills/filter-pills.component.tsx

Fixes #1505
Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/677

fix: pill text overflow and use svg cross icon

---

package-lock.json
package.json
src/components/community/comments/components/comment-card/index.tsx
src/components/community/comments/components/comment-card/styled.ts
webpack/dev.config.ts
webpack/prod.config.ts

fix: support code block and highlighting

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/ai-project-page/index.tsx
src/pages/ai-project-page/styled.ts

closes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/704

feat: add contact info ai-page

---

src/components/public-service-details-page/index.tsx

fix: bugfix all languages showing for keywords

---

src/entrypoints/publishing/router/publishing/pages/publishing-page/index.tsx
src/l10n/nb.json

fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1638
resolves https://github.com/Informasjonsforvaltning/fdk-portal/issues/1464

fix: broken guidance link to open data

---

src/components/details-page/components/side-menu/styled.ts

fix: use correct menu width

---

src/components/dataset-item/dataset-item.component.tsx
src/components/dataset-item/dataset-item.styled.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/417

feat: dataset item filter on label click

---

src/components/article/components/article/styled.ts
src/components/dataset-item/dataset-item.component.tsx
src/components/dataset-item/dataset-item.styled.tsx
src/components/details-page/components/details-page/styled.ts
src/components/markdown/index.tsx
src/components/search-hit/components/search-hit/__tests__/__snapshots__/search-hit.component.test.tsx.snap
src/components/search-hit/components/search-hit/search-hit.component.tsx
src/components/search-hit/components/search-hit/styled.ts
src/pages/cms-information-page/styled.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/671

chore: improve identification of hyperlinks

---

src/components/header/index.tsx
src/entrypoints/main/index.html
src/pages/news-archive-page/news-archive-page-pure.tsx
src/pages/organizations/pages/dataset-page/index.tsx
src/pages/organizations/pages/datasets-page/index.tsx
src/pages/organizations/pages/organization-page/index.tsx
src/pages/organizations/pages/organizations-page/index.tsx
src/pages/report-page/report-page-pure.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/666
Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/680

fix: move skip link to first element and use correct hidden value

---

package-lock.json
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/organizations/pages/organization-page/index.tsx
src/types/domain.d.ts

feat: show number of employees on organization-page

---

src/components/details-page/components/banner/index.tsx

fix: resilient workaround dom mutations google translate

---

package-lock.json
package.json

fix: breadcrumbs wrapping after bootstrap upgrade

---

src/components/concept-item/concept-item.component.tsx

quick fix for #1731
closes #1731 (eller la det være åpent?)

fix: not displaying text

---

src/api/datasetPreview.js
src/components/with-dataset-preview/redux/saga.ts

chore: fetch csrf from endpoint

---

package-lock.json
src/components/concept-details-page/index.tsx
src/l10n/nb.json
src/types/domain.d.ts
src/utils/date/index.ts

resolves https://github.com/Informasjonsforvaltning/fdk-portal/issues/1740

feat(concept): add date created

---

src/components/with-concepts/redux/saga.ts
src/l10n/en.json
src/l10n/nn.json
src/pages/concept-details-page/RelatedConcepts/index.tsx

resolves https://github.com/Informasjonsforvaltning/fdk-portal/issues/1759
Legger til nytt relasjonsfelt *Medlem av/Member* Of i begrepsdetaljvisningen.

feat(concept): add memberOf to detail page

---

src/components/details-page/components/key-value-list/index.tsx
src/pages/concept-details-page/RelatedConcepts/AssociativeRelations/index.tsx
src/pages/concept-details-page/RelatedConcepts/GenericRelations/index.tsx
src/pages/concept-details-page/RelatedConcepts/IsReplacedBy/index.tsx
src/pages/concept-details-page/RelatedConcepts/MemberOf/index.tsx
src/pages/concept-details-page/RelatedConcepts/PartitiveRelations/index.tsx
src/pages/concept-details-page/RelatedConcepts/SeeAlso/index.tsx
src/pages/concept-details-page/RelatedConcepts/index.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/729
closes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1749

fix(concept): show all relation fields

---

src/app/app-nav-bar/app-nav-bar.tsx

feat: add chevron down to menu items

---

package-lock.json
package.json
src/app/app.jsx
src/components/banner/index.tsx
src/components/banner/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/requests/index.tsx
src/pages/requests/styled.ts

feat: add ingress requests page

---

package-lock.json

fix: fix audit

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/requests/index.tsx

feat: small changes

---

src/pages/dataset-details-page/index.tsx

fixes: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/827

fix: show related concepts not in fdk

---

src/l10n/nb.json
src/pages/ai-project-page/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1827

chore: remove guidance link

---

src/pages/search-page/filters/index.tsx

part of https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/837

chore: rm filterbox for event types

---

src/api/generated/cms/graphql.ts
src/lib/strapi/index.ts
src/pages/cms-information-page/index.tsx
src/pages/cms-transport-page/index.tsx
src/pages/fancy-article-page-v2/fancy-article-page.tsx
src/pages/news-article-page-v2/news-article-page.tsx
src/services/api/strapi/graphql/fancy-article.graphql
src/services/api/strapi/graphql/news-article.graphql
src/services/api/strapi/graphql/transport-article.graphql

Fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1836

fix: language support strapi

---

src/components/analytics-ga/index.tsx
src/components/analytics-monsido/index.tsx
src/components/analytics-siteimprove/index.tsx
src/entrypoints/main/bootstrap.tsx
src/entrypoints/main/index.html
src/entrypoints/publishing/app/index.tsx
src/entrypoints/publishing/index.html

chore: refactor analytics

---

src/components/analytics-monsido/index.tsx

fix: monsido tracking code

---

src/pages/concept-compare-page/concept-compare-page.tsx
src/pages/organizations/pages/dataset-page/index.tsx
src/pages/organizations/pages/datasets-page/index.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/669

fix: add th scope

---

package-lock.json
package.json

fixer en feil som gjorde at forrige commit i develop ikke ble deployet til staging

fix: override puppeteer version

---

src/pages/search-page/search-page-pure.tsx
src/pages/search-page/tabs/components/tabs/tabs.component.tsx

fix: remove number in all tab for search hits

---

src/l10n/nb.json
src/pages/search-page/search-box/hits-stats/hits-stats.component.test.tsx
src/pages/search-page/search-box/hits-stats/hits-stats.component.tsx
src/pages/search-page/search-page-pure.tsx
src/pages/search-page/tabs/components/tabs/__tests__/tabs.component.test.tsx
src/pages/search-page/tabs/components/tabs/tabs.component.tsx

feat: add count for public services and revents in search page title

---

package-lock.json
package.json

fikser auditfeil som hindret deploy til staging

fix: audit axios

---

src/pages/dataset-details-page/index.tsx
src/pages/information-model-details-page/index.tsx
src/pages/public-service-details-page/index.tsx

fix: make keywords on details page use search instead of filter

---

deploy/staging/env.yaml

Legger til secret for fdk-resource-service

fix: add resource api env

---

package-lock.json
src/api/resource-service-api/concepts.ts
src/api/resource-service-api/host.ts
src/pages/concept-compare-page/concept-compare-page.tsx
src/pages/concept-compare-page/connected-concept-compare-page.jsx
src/redux/modules/fullConceptsCompare.js
src/redux/rootReducer.js

feat(concept-compare): get concepts from resource service

---

src/components/dataset-item/dataset-item.component.tsx
src/types/domain.d.ts

~~Må vente på reindeksering før vi har faktisk data på isAuthorative så får ikke sjekket om det fungerer før da~~
Ferdig testet
closes #1948

fix: make isAuthoritative icon on datasets support new structure

---

README.md
docker-compose.yml

Oppdaterte dokumentasjon for hvordan miljøvariabler legges til i portal.

chore: update documentation

---

src/pages/search-page/filters/index.tsx

fix: open data not showing in filter boxes

---

src/components/with-concepts/redux/saga.ts
src/components/with-data-services/redux/saga.ts
src/components/with-datasets/redux/saga.ts
src/components/with-events/redux/saga.ts
src/components/with-information-models/redux/saga.ts
src/components/with-public-services-and-events/redux/saga.ts
src/components/with-public-services/redux/saga.ts
src/components/with-resource-relations/redux/saga.ts
src/pages/search-page/search-page-resolver.ts
src/redux/modules/catalogs.js
src/redux/modules/concepts.js
src/redux/modules/dataservices.js
src/redux/modules/datasets.js
src/redux/modules/informationModels.js
src/redux/modules/publishers.js
src/redux/modules/referenceData.js
src/types/domain.d.ts
src/utils/common/index.ts

Fikser searchparams mapping feil
Fixes #2000

Searchparams mapping feil

---

src/pages/concept-compare-page/concept-compare-page.tsx
src/redux/modules/fullConceptsCompare.js

Bruk resource api concepts by ids

fix: use resource api concepts by ids for comparison

---

src/components/filter-option/filter-option.component.tsx
src/pages/search-page/filter-pills/filter-pills.component.tsx
src/pages/search-page/filter-tree/filter-tree.component.tsx
src/utils/common/index.ts

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/922

handle filter value null

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

fix: text not showing for datalandsbyen section

---

src/components/data-service-item/data-service-item.component.tsx
src/components/dataset-item/dataset-item.component.tsx
src/utils/common/index.ts

closes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/923

fix: show format name instead of code in search hits

---

src/components/with-datasets/redux/reducer.ts
src/components/with-information-models/redux/reducer.ts
src/redux/modules/catalogs.js
src/redux/modules/concepts.js
src/redux/modules/conceptsCompare.js
src/redux/modules/dataservices.js
src/redux/modules/datasets.js
src/redux/modules/fullConceptsCompare.js
src/redux/modules/informationModels.js
src/redux/modules/publishers.js
src/redux/modules/referenceData.js

Unngå at redux havner i en loop

fix: do not retry on redux failure

---

src/app/app-nav-bar/app-nav-bar.tsx
src/constants/constants.js
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

closes https://github.com/Informasjonsforvaltning/fdk-portal/issues/2018

feat: add link to datahunter in header

---

src/pages/organizations/pages/organization-page/index.tsx

Klarte ikke å finne noen andre steder i koden hvor den gamle adressen brukes.

fix: updated url for fetching orglogos

---

src/components/details-page/components/details-page/index.tsx
src/components/details-page/components/details-page/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/types/domain.d.ts
src/white-list.ts

resolves https://github.com/Informasjonsforvaltning/fdk-portal/issues/2041

feat: resource access request

---

src/components/infomodel-structure/model-element-list/element/styled.ts

Ref: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/618

fix: added white-space:nowrap rules to prevent words breaking in infomodel-structure

---

src/api/generated/cms/graphql.ts
src/entrypoints/publishing/router/publishing/pages/publishing-page/index.tsx
src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx

Support service messages for demo

feat: add service message for demo

---

src/components/with-reference-data/redux/saga.ts
src/pages/concept-details-page/Description/index.tsx
src/pages/concept-details-page/Description/styled.ts
src/pages/concept-details-page/index.tsx
src/types/domain.d.ts
src/utils/common/index.ts

chore: update concept definition according to skos v2

---

docker-compose.yml
src/env.ts
src/pages/search-page/results-all-entities/results-all-entities.component.tsx
src/types/env.d.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/953
FIxes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/954

fix: replace invalid SEARCH_API_HOST with FDK_PORTAL_BASE_URI

---

package-lock.json
package.json

Fikser bug i prod hvor paginering blir rendret uten stiler
Ref. https://fdk-project.slack.com/archives/C7D69GE8L/p1717744113452079

fix: roll back design-system-react

---

src/app/app-nav-bar/app-nav-bar.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/959

fix: add missing links to mobile header

---

src/entrypoints/main/index.html

fixes https://github.com/Informasjonsforvaltning/fdk-portal/issues/1677

fix: skip to content

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/public-service-details-page/index.tsx
src/types/domain.d.ts

fixes: #1621 
Trenger at endring i fdk-rdf-parser merges: https://github.com/Informasjonsforvaltning/fdk-rdf-parser/pull/315

fix: show service type

---

src/components/details-page/components/banner/index.tsx
src/components/details-page/components/banner/styled.ts
src/components/details-page/components/details-page/index.tsx
src/components/details-page/components/details-page/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/107
closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/109
closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/108

feat: update design details page banner

---

src/app/breadcrumbs/concept-breadcrumb/index.tsx
src/app/breadcrumbs/data-service-breadcrumb/index.tsx
src/app/breadcrumbs/dataset-breadcrumb/index.tsx
src/app/breadcrumbs/event-breadcrumb/index.tsx
src/app/breadcrumbs/informationModel-breadbrumb/index.tsx
src/app/breadcrumbs/public-service-breadcrumb/index.tsx
src/components/details-page/components/RelatedConcepts/index.tsx
src/components/details-page/components/banner/index.tsx
src/components/details-page/components/banner/styled.ts
src/components/details-page/components/content-section/index.tsx
src/components/details-page/components/details-page/index.tsx
src/components/details-page/components/details-page/styled.ts
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json
src/pages/concept-details-page/index.tsx
src/pages/data-service-details-page/index.tsx
src/pages/dataset-details-page/index.tsx
src/pages/event-details-page/index.tsx
src/pages/information-model-details-page/index.tsx
src/pages/information-model-details-page/styled.ts
src/pages/public-service-details-page/index.tsx
src/utils/common/index.ts

closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/126
(skal squash'e)

Andre iterasjon av design-endringer på detaljsidene

---

src/components/concept-item/styled.ts
src/components/dataset-item/dataset-item.component.tsx
src/components/details-page/components/details-page/index.tsx
src/components/details-page/components/details-page/styled.ts
src/components/rounded-tag/styled.ts
src/components/search-hit/components/search-hit-head/__tests__/__snapshots__/search-hit_head.component.test.tsx.snap
src/components/search-hit/components/search-hit-head/search-hit-head.component.tsx
src/components/search-hit/components/search-hit-head/styled.ts
src/components/search-hit/components/search-hit/__tests__/__snapshots__/search-hit.component.test.tsx.snap
src/components/search-hit/components/search-hit/search-hit.component.tsx
src/components/search-hit/components/search-hit/styled.ts
src/components/truncated-text/styled.ts
src/pages/dataset-details-page/styled.ts

closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/111

feat: new design search-hit box

---

src/components/button-toggle/styled.ts
src/pages/search-page/sort-buttons/styled.ts
src/pages/search-page/tabs/components/tabs/styled.ts
src/pages/search-page/tabs/components/tabs/tabs.component.tsx

closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/110
closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/112
Ser slik ut nå:

feat: update design for tabs

---

src/pages/dataset-details-page/index.tsx
src/types/domain.d.ts

feat: handle dataset types as both string and object

---

.github/workflows/deploy-prod&demo.yaml
.github/workflows/deploy-staging.yaml

Old main branch is renamed to "main_archived", old "develop" branch is now "main"

chore: Alter deploy files in accordance to new flow.

---

src/pages/dataset-details-page/index.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/891
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/892

fix: prioritize uri-field when searching for concepts related to dataset

---

src/pages/ai-project-page/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/995

fix: replace deprecated email address

---

src/white-list.ts

Hallois 👋  Takk for workshop i går! Vi trenger at linken her ikke lenger peker POCen under kystverket, men på løsningen som nå ligger under digdir 🙌

Replace white list requestAddress for Samferdselsdata in staging

---

src/white-list.ts

Samme som https://github.com/Informasjonsforvaltning/fdk-portal/commit/9eb8449213237579d40bcc05d60e8086fcbef196, men for prod 🚀 
Endrer fra kystverket sin app til appen som ligger under digdir

Replace white list requestAddress for Samferdselsdata in prod

---

package-lock.json
package.json
src/components/details-page/components/banner/index.tsx
src/components/details-page/components/banner/styled.ts

fix: render additional languages

---

src/components/community/user/index.tsx
src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

I formindelse med nodebb v3 så skal vi håndtere brukere som ikke finnes lenger.

fix: show former user if user is removed

---

src/white-list.ts

Gjør så vi får link til kudafsøknaden på denne data servicen: https://staging.fellesdatakatalog.digdir.no/data-services/ecdbd6d4-7026-3731-bd8e-2f15e26221a2

Add SVV test case to white list

---

src/white-list.ts

Legg til link til kudaf på test av fakedoor datasettet
https://staging.fellesdatakatalog.digdir.no/datasets/26a075d7-f92a-381f-8831-291ae8aa63a4

Add fakedoor dataset to whitelist

---

src/white-list.ts

Legger til dette datasettet: https://staging.fellesdatakatalog.digdir.no/data-services/57cd0ad7-2602-3a3a-894e-fde19b29980e i whitelist

Legg til tenor testdata i whitelist

---

src/l10n/en.json
src/l10n/nb.json
src/l10n/nn.json

Update the description under the option Register data on the page data.norge.no/publishing

feat: update description to Register data

---

src/components/details-page/components/RelatedConcepts/GenericRelations/index.tsx
src/components/details-page/components/RelatedConcepts/IsReplacedBy/index.tsx
src/components/details-page/components/RelatedConcepts/PartitiveRelations/index.tsx

resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1092
Se feks denne: https://staging.fellesdatakatalog.digdir.no/concepts/c818cc88-e929-4416-9160-0d481d9157f8
i registrering:
i portal:

fix: show all concept relations

---

src/pages/data-service-details-page/index.tsx

resolves https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1177

fix: removed usage of RouteLink in dataset-references list under data-service-details-page

---

src/pages/organizations/pages/dataset-page/styled.ts
src/pages/organizations/pages/datasets-page/styled.ts

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1200

Fix: color contrast, metadata quality pages
