- .github/workflows/deploy-staging-digdir.yaml
- .github/workflows/deploy-staging.yaml
Mtp høy kollisjonsfare for pull requester i dette repoet kan vi prøve en annen deploy-prosess her, dette burde fungere som en midlertidig løsning for usikkerhet rundt hva som er deployet til it1.
Merge til develop -> deploy til it1/staging
Merge/cherry-pick av develop inn i master -> deploy til prod og demo
> feat: deploy to staging on merge to develop

- src/pages/informationmodel-details-page/information-model-details-page.jsx
Hoved issue ble fikset her:
https://app.zenhub.com/workspaces/fdk---felles-datakatalog-5c61461c801d5a1030316315/issues/informasjonsforvaltning/fdk/3077
Fikser bare en liten front-end bug med visning-logikk.
> chore: #3045 fix information model status display logic

- src/pages/data-service-details-page/data-service-details-page.jsx
Har denne mapping i dataservice-catalog-gui:
export enum ServiceType {
CUSTOMER_RELATIONS = 'CUSTOMER_RELATIONS',
ACCOUNT_DETAILS = 'ACCOUNT_DETAILS'
}
og mapper det om til code som brukes i referansedata (https://staging.fellesdatakatalog.digdir.no/reference-data/codes/apiservicetype):
const serviceTypeCodeMapping = {
CUSTOMER_RELATIONS: 'Kundeforhold',
ACCOUNT_DETAILS: 'Kontoopplysninger'
};
> fix(data-service-details-page): fix servicetype code mapping

- src/components/infomodel-structure/model-element-list/index.tsx
- src/components/information-model-details-page/index.tsx
- src/types/domain.d.ts
Det ble generert en ny array med conceptReferences hver render. Ny object referanse => ny render. Så løsningen er å joine den å gjøre den om til string.
> fix: prevent infinite loop of requests to fetch concepts

- src/api/search-fulltext-api/datasets.ts
- src/api/search-fulltext-api/informationmodels.ts
- src/components/details-page/components/details-page/index.tsx
- src/components/infomodel-structure/__tests__/__snapshots__/infomodel-structure.component.test.tsx.snap
- src/components/infomodel-structure/infomodel-structure.component.tsx
- src/components/infomodel-structure/model-description/model-description.component.tsx
- src/components/infomodel-structure/model-element-list/element/index.tsx
- src/components/infomodel-structure/model-element-list/index.tsx
- src/components/information-model-details-page/index.tsx
- src/components/with-concepts/redux/action-types.ts
- src/components/with-concepts/redux/actions.ts
- src/components/with-concepts/redux/reducer.ts
- src/l10n/en.json
- src/l10n/nb.json
- src/l10n/nn.json
- src/types/domain.d.ts
-fixed keywords links and filter on datasets and inforrmation models
- fixed responsible vs owner on detail page
- fixed specialization references on information models
- fixed concept references on information models structure
- fixed issue on reports page where APIs showing 0
- fixed issue where user was not taken to correct attribute when clicking the attribute on information model structure page
> prodsetting portal

- src/components/concept-details-page/index.tsx
> fix(concept-details-page): invalidate selected languages when unmount

- src/pages/organizations/pages/datasets-page/index.tsx
Luna fant et problem: `getAssessments` bruker `page` fra forrige gang det ble hentet, så prøver å hente page 1 om du går inn på datasettene til en ny organisasjon etter å ha lastet inn flere datasett for forrige
> fix: set page number like 0 when fetching initial organization assessments

- src/pages/search-page/results-all-entities/results-all-entities.component.tsx
- src/pages/search-page/sort-buttons/index.tsx
- src/pages/search-page/sort-buttons/styled.ts
I mobilvisning ha sorteringsknappene til å ligge ved siden av og fylle ut hele bredden.
> fix(sort-buttons): change responsive styling

- src/entrypoints/main/index.html
Script fra Questback, skal vise en popup på fdk-portal til brukerundersøkelse, gjelder ikke for Transportportal.
> feat(index.html): add questback popup

- .env.example
- .gitignore
- .prettierrc
- src/config.js
Small developer improvement, adds a `.prettierrc` which makes it possible to use in-editor Prettier (like format on save etc).
Adds an example dotenv file, along with an gitignore entry for that file.
> chore: add dotenv and prettierrc

- src/lib/translateText.js
> fix: support empty string as fallback language

- src/components/markdown/index.tsx
> fix: add error boundary to markdown component (chrome translate bug)

- src/services/api/harvester-bff/index.ts
Mange komponenter bruker destructuring av attributter, det fungerer ikke hvis verdien er NULL fra api. Som enkel løsning, fjerner NULL-verdier før det gis til komponenten.
> fix(harvester-bff): remove null values

- src/components/event-details-page/index.tsx
- src/components/event-item/index.tsx
fixes #1223 
Klarer nå å vise hendelsen "Vedtak om skjenkebevilling":
> fix: handle events with missing specialized_type value

- src/components/dataset-details-page/index.tsx
fixes #1347 
Var visst krav om å ha url for at navn skulle vises, la til at kontaktdetaljer vises navn som ikke er link når url ikke er tilgjengelig.
eksempel hvor navn er tilgjengelig, men ikke url:
eksempel hvor både navn og url er tilgjengelig:
> fix: show dataset contact details name when url is missing

- src/pages/search-page/results-all-entities/results-all-entities.component.tsx
> fix: #1342 - shows "no results found" when loading page

- .eslintrc.json
Er en regel eslinter har for imports i typescript som trigger når man gjør endringer, det er bare en regel som skal gjøre importer mer generiske og ikke kombinere declerations og expressions (sånn jeg forsto den). Lagt inn en ignore for denne regelen i eslinter som gjør at man får commited kode til branch uten å få feil i importer som man ellers ikke hadde rørt i kodeendringen sin uansett.
Alternativer er at ved hver gang man gjør en kodeendring i en fil så må man fixe importen slik at eslinter regelen blir fornøyd, uten at det egentlig skal ha noe påvirkning på noe annet enn blidgjøre regelen å gjøre disse import endringene ser jeg ikke behovet for å faktisk ta den jobben, og heller da har ignore slik at man faktisk får pushet kode til repo. 
Men kjører gjerne en debatt om noen har andre …
> fix: changed eslinter to ignore importing rules

- src/components/public-service-details-page/index.tsx
beskrivelse shows even though object does not have beskrivelse #1484
> fix: closes #1484 bug - "description" shows when no description

- .pa11yci
- package.json
- src/components/expansion-indicator-default/index.tsx
- src/components/treeview/index.tsx
Ignored rules: 
- Duplicate id attribute value "[Element ID]" found on the web page.
- Form does not contain a submit button (input type="submit", input type="image", or button type="submit").
- Heading tag found with no content. Text that is not intended as a heading should not be marked up with heading tags.
- Img element missing an alt attribute. Use the alt attribute to specify a short text alternative.
- This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of {value}. Recommendation: {colour recommendations}.
> feat: make pa11y tests succeed 

- src/components/concept-details-page/index.tsx
- src/types/domain.d.ts
Regner med at det kommer nytt design på dette senere, nå i første omgang legger jeg bare opp til at den klarer å vise alt i gammelt design.
Eksempel på begrep med lang liste literals i fagområde-feltet:
Eksempel på hvordan det ser ut for noen som har valgt fagområde fra kodeliste i registrering:
> chore: handle concept subjects as list of objects

- src/components/concept-details-page/index.tsx
- src/utils/date/index.ts
- skjuler "Begrepsinformasjon"-boksen når det er ingen info å vise.
- defaulter outputen av isoFormat til å være det formatet som er mest spredt i våre kodebaser.
> fix(concept): hide empty fields

- src/api/community-api/search.ts
- src/components/with-community/index.tsx
- src/components/with-community/redux/action-types.ts
- src/components/with-community/redux/actions.ts
- src/components/with-community/redux/reducer.ts
- src/components/with-community/redux/saga.ts
- src/pages/requests/index.tsx
- src/pages/requests/styled.ts
- src/types/domain.d.ts
> feat: add data to requests page

- src/components/details-page/components/details-page/index.tsx
A fix to open the link in a new tab after clicking on the access request button.
> fix: open access request link in new a tab

- src/components/details-page/components/details-page/index.tsx
- src/components/details-page/components/key-value-list/index.tsx
- src/components/details-page/components/list/index.tsx
- src/pages/public-service-details-page/index.tsx
- src/pages/requests/index.tsx
- Fjerner tom/ubrukt `<Breadcrumbs />`-komponent på Requests page
- Betinget rendring av Theme kontainer på DetailsPage kun hvis den har barn
- Betinget rendring av `<ul></ul>` kontainer i KeyValueList kun hvis den har barn
- Oppdatert hver instans hvor DetailsPage/List-komponenten blir brukt til å wrappe barna i `<li>`-elementer, la også til betinget rendring av `<ul></ul>` kun hvis den har barn
Resolves #1843
> fix: empty container elements (invalid html siteimprove error)

- src/components/details-page/components/details-page/index.tsx
closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/105
closes https://github.com/Informasjonsforvaltning/fdk-portal/issues/2019
Problem: Lenkene i sticky menyen blir laget ved å se på barna til en detaljside og sjekke om det er av type ConcentSection og om de har tittel og id. På detaljsiden til begrep er det blitt gjort en refakturering slik at alle contentSections er wrappet i en annen komponent, som gjør at funksjonen ikke finner noen barn av type contentSection. 
Kan løses vist man vil, men da må man enten 1) refakturere sticky meny komponenten (best men mye jobb), 2) hacky løsning 3) "tilbakestille" refaktureringen. 
Da ingen av disse løsningene er spesielt gunstige konkluderte vi med at det beste er å fjerne menyen helt KUN på begrep sin detaljside, da menyen …
> fix: remove sticky menu from concept details page

- src/white-list.ts
Adding the application button for the dataset https://staging.fellesdatakatalog.digdir.no/datasets/86e664de-e8b4-355a-bdec-56724eb07900. The application can be found here: https://digdir.apps.tt02.altinn.no/digdir/tilgangsoknad-svv/
> Add tilgangsoknad-svv in staging

- src/white-list.ts
[Tenor](https://skatteetaten.github.io/testnorge-tenor-dokumentasjon/#:~:text=Hvordan%20f%C3%A5%20tilgang%20til%20API%2Det%20for%20s%C3%B8k&text=For%20%C3%A5%20f%C3%A5%20tilgang%20m%C3%A5,til%20s%C3%B8ke%2DAPI'et.) ha nå gitt tommel opp for å ha [dette APIet](https://data.norge.no/data-services/95b9c74d-1dd4-3f92-aef2-a6a587b03fb3) som en del av søknadsløsningen i prod 🚀 
Legger det til med link til [søknaden i Altinn](https://digdir.apps.altinn.no/digdir/tilgangssoknad-tenor/)
> Add tenor to white list in prod

- src/white-list.ts
Entur har kommet så langt i sin datakatalog at å gå via søknaden vi har laget bare er en omvei. Raskeste er å gå til deres katalog som allerede linkes til på datanorge. 
https://data.entur.no/domain/public-transport-data
> Fjern Entursøknad

- package-lock.json
- src/pages/organizations/pages/organization-page/index.tsx
Må sannsynligvis jobbe en del med hele mqa-løpet før vi kan fikse dette på en god måte, har oppretta dette for å ta tak i problemet senere: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1059
Så på kort sikt bare deaktiverer vi
> chore: hide mqa score on org page when missing mqa data
